#!/bin/bash
# Build & Run Guide

echo "═══════════════════════════════════════════════════════════════════"
echo "  Gideon Peprah Ministries & Valour Multimedia - Complete Setup"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Project Structure:"
echo "   • 2 independent brands with shared components"
echo "   • 9 main pages + landing page selector"
echo "   • Mobile-first responsive design"
echo "   • Custom Tailwind color system"
echo ""
echo "📁 File Structure:"
echo "   • app/components/ - 4 reusable components (Button, Card, Header, Footer)"
echo "   • app/ministry/ - 5 pages (home, live, events, give, contact)"
echo "   • app/multimedia/ - 4 pages (home, services, portfolio, contact)"
echo "   • app/page.tsx - Split landing selector"
echo ""
echo "🎨 Tailwind Custom Colors:"
echo "   • Primary Green: #0F3D2E"
echo "   • Accent Gold: #D4AF37"
echo "   • White Background: #FFFFFF"
echo "   • Dark Text: #1F2937"
echo "   • Muted Text: #6B7280"
echo ""
echo "📱 Responsive Breakpoints:"
echo "   • Mobile: default styles"
echo "   • Tablet (sm: 640px): adjustments"
echo "   • Desktop (md: 768px): grid layouts"
echo "   • Large Desktop (lg: 1024px): full experience"
echo ""
echo "🔌 Integration Points Ready:"
echo "   • Payment gateway (ministry/give)"
echo "   • Live streaming embeds (ministry/live)"
echo "   • Portfolio media uploads (multimedia/portfolio)"
echo "   • Form submissions (both contact pages)"
echo "   • Newsletter signup (ministry/events)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 Getting Started:"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "📊 Build for Production:"
echo "   npm run build"
echo "   npm start"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
